django_3/project_site/djbr/urls.py
from django.urls import path

from . import views

app_name = 'djbr'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.index, name='books'),
    path('books/<int:book_id>/', views.book, name='book'),
    path('books/<int:book_id>/reviews/', views.reviews, name='reviews'),
    path('books/<int:book_id>/reviews/<int:review_id>/',
        views.review, name='review'),    
    path('authors/<int:author_id>/', views.author, name='author'),
]

django_3/project_site/djbr/models.py
from django.db import models
from django.utils import timezone

class Book(models.Model):
    title = models.CharField(max_length=200)
    pub_year = models.IntegerField('date published', default=2000)

    def was_published_recently(self):
        return (self.pub_year >= timezone.now().year - 1)

    def __str__(self):
        return "%s %s" % (self.title, self.pub_year)

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField(default="")
    review_date = models.DateTimeField('review date')

    def __str__(self):
        return "%s %s %s" % (self.title, self.text, self.review_date)


class Author(models.Model):
    name = models.CharField(max_length=200)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.name

django_3/project_site/djbr/views.py
from django.shortcuts import render, get_object_or_404

from django.urls import reverse
from django.utils import timezone
from django.http.response import HttpResponseRedirect

from .models import Book, Author, Review

def index(request):
    latest_books_published = Book.objects.order_by('-pub_year', 'title')[:10]
    context = {'latest_books_published': latest_books_published}
    return render(request, 'djbr/index.html', context)

def book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'djbr/book.html', {'book': book})

def reviews(request, book_id):
    book_reviews = Review.objects.filter(book_id=book_id)
    return render(request, 'djbr/reviews.html',
                  {'book_reviews': book_reviews })

def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'djbr/author.html', {'author': author})

def review(request, book_id, review_id=None):
    
    if review_id is not None:
        review = get_object_or_404(Review, pk=review_id)
    else:
        review = Review()
        review.book_id = book_id

    if request.method == 'POST':
        review.title = request.POST['title']
        review.text = request.POST['text']
        review.review_date = timezone.now()
        review.save()
        return HttpResponseRedirect(reverse('djbr:reviews',
                                            args=(book_id,)))
    else:
        context = {
        'book_id': book_id,
        'review_id': review_id,
        'title': review.title,
        'text': review.text
    }
    
    return render(request, 'djbr/review.html', context)

django_3/project_site/djbr/templates/djbr/author.html
{% extends "djbr/base.html" %}

{% block content %}
<ul class="list-group">
  <li class="list-group-item">
    Name: {{ author.name }}
  </li>
  <li class="list-group-item">
    Books:
    <ul>
      {% for book in author.books.all %}
	<li>
	  <a href="{% url 'djbr:book' book.id %}">{{ book.title }}</a>
	</li>
      {% endfor %}
    </ul>
</ul>
{% endblock %}

django_3/project_site/djbr/templates/djbr/base.html
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags for Bootstrap -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1,
          shrink-to-fit=no">

    {% load static %}

    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="{% static "/djbr/css/fontawesome-all.min.css" %}"/>

    <link rel="stylesheet"
          href="{% static "/djbr/css/djbr.css" %}"/>
	  
    <!-- Bootstrap CSS -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
          crossorigin="anonymous">

    <title>{% block title %}Django Book Reviews{% endblock %}</title>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>{% block heading %}Django Book Reviews{% endblock %}</h1>
      </div>
      <div class="col-md-offset-1 col-md-6">
        {% block content %}{% endblock %}
      </div>
    </div>

    <!-- Optional JavaScript for Bootstrap --> 
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

django_3/project_site/djbr/templates/djbr/book.html
{% extends "djbr/base.html" %}

{% block content %}
<ul class="list-group">
  <li class="list-group-item">
	Title: {{ book.title }}
  </li>
  <li class="list-group-item">
	Author:
	<ul>
	  {% for author in book.author_set.all %}
		<li>
		  <a href="{% url 'djbr:author' author.id %}">{{ author.name }}</a>
		</li>
	  {% endfor %}
	</ul>
  <li class="list-group-item">
	Year published: {{ book.pub_year }}
  </li>
  <li class="list-group-item">
	<span>Reviews:
	<a href="{% url 'djbr:reviews' book.id %}">
	  <span class="badge badge-secondary">{{ book.review_set.all.count }}</span>
	</a>
	<a href="{% url 'djbr:reviews' book.id %}">
	  <span class="fas fa-plus-circle" aria-hidden="true"></span>
	</a>
	</span>
  </li>
</ul>
{% endblock %}

django_3/project_site/djbr/templates/djbr/index.html
{% extends "djbr/base.html" %}

{% block content %}
{% if latest_books_published %}
  <ul class="list-group">
    {% for book in latest_books_published %}
      <li class="list-group-item">
	<a href= "{% url 'djbr:book' book.id %}">{{ book.title }}</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No books are available.</p>
{% endif %}
{% endblock %}

django_3/project_site/djbr/templates/djbr/review.html
{% extends "djbr/base.html" %}

{% block content %}
{% if review_id %}
<form action="{% url 'djbr:review' book_id review_id %}"  method="post">
{% else %}
<form action="{% url 'djbr:reviews' book_id %}"  method="post">
{% endif %}
  {% csrf_token %}
    <div class="form-group">
    <label for="title">Title</label>
    <input type="text" id="title" name="title"
           class="form-control" placeholder="Title" value="{{ title }}"/>
  </div>
  <div class="form-group">
    <label for="text">Content</label>
    <textarea id="text" name="text"
              class="form-control" placeholder="content" rows="10">{{ text }}
    </textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>  
{% endblock %}

django_3/project_site/djbr/templates/djbr/reviews.html
{% extends "djbr/base.html" %}

{% block content %}
{% if not book_reviews %}
  <h2 class="bg-warning">No reviews yet.</h2>
{% else %}
  <div class="list-group">
    {% for review in book_reviews %}
      <div class="list-group-item list-group-item-action flex-column
                  align-items-start active">
        <div class="d-flex w-100 justify-content-between">
          <span class="mb=1">Summary: {{ review.title }}</span>
          <span>
            <a href="{% url 'djbr:review' review.book.id review.id %}">
              <span class="fas fa-inverse fa-edit" aria-hidden="true"></span>
            </a>
        </span>
        </div>
      </div>
      <div class="list-group-item">
        Review: {{ review.text }}
      </div>
      <div class="list-group-item">
        Date reviewed: {{ review.review_date }}
        {{ review.id }}
      </div>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}