django_2/project_site/djbr/urls.py
from django.urls import path

from . import views

app_name = 'djbr'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/<int:book_id>/', views.book, name='book'),
    path('books/<int:book_id>/reviews/', views.reviews, name='reviews'),
    path('authors/<int:author_id>/', views.author, name='author'),
]

django_2/project_site/djbr/views.py
from django.shortcuts import render, get_object_or_404

from .models import Book, Author, Review

def index(request):
    latest_books_published = Book.objects.order_by('-pub_year', 'title')[:10]
    context = {'latest_books_published': latest_books_published}
    return render(request, 'djbr/index.html', context)

def book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'djbr/book.html', {'book': book})

def reviews(request, book_id):
    book_reviews = Review.objects.filter(book_id=book_id)
    return render(request, 'djbr/reviews.html',
                  {'book_reviews': book_reviews })

def author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'djbr/author.html', {'author': author})

django_2/project_site/djbr/templates/djbr/base.html
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags for Bootstrap -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1,
          shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
          crossorigin="anonymous">

    <title>{% block title %}Django Book Reviews{% endblock %}</title>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>{% block heading %}Django Book Reviews{% endblock %}</h1>
      </div>
      <div class="col-md-offset-1 col-md-6">
        {% block content %}{% endblock %}
      </div>
    </div>

    <!-- Optional JavaScript for Bootstrap --> 
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

django_2/project_site/djbr/templates/djbr/book.html
{% extends "djbr/base.html" %}

{% block content %}
<ul class="list-group">
  <li class="list-group-item">
    Title: {{ book.title }}
  </li>
  <li class="list-group-item">
    Author:
    <ul>
      {% for author in book.author_set.all %}
	<li>
	  <a href="{% url 'djbr:author' author.id %}">{{ author.name }}</a>
	</li>
      {% endfor %}
    </ul>
  <li class="list-group-item">
    Year published: {{ book.pub_year }}
  </li>
  <li class="list-group-item"><span>Reviews:
    <a href="{% url 'djbr:reviews' book.id %}">
      <span class="badge badge-secondary">{{ book.review_set.all.count }}
      </span>
  </li>
</ul>
{% endblock %}

django_2/project_site/djbr/templates/djbr/reviews.html
{% extends "djbr/base.html" %}

{% block content %}
{% if not book_reviews %}
  <h2 class="bg-warning">No reviews yet.</h2>
{% else %}
  <div class="list-group">
    {% for review in book_reviews %}
      <div class="list-group-item active">
	Summary: {{ review.title }}
      </div>
      <div class="list-group-item">
	Review: {{ review.text }}
      </div>
      <div class="list-group-item">
	Date reviewed: {{ review.review_date }}
      </div>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}